services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
